//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.VideoClub.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        public int id_incidencia { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_tipo_inc { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual tipo_incidencia tipo_incidencia { get; set; }
    }
}
