//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.VideoClub.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id_item { get; set; }
        public Nullable<int> id_producto { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> id_incidencia { get; set; }
    
        public virtual incidencia incidencia { get; set; }
        public virtual producto producto { get; set; }
    }
}
