//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.VideoClub.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public juego()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id_juego { get; set; }
        public string titulo { get; set; }
        public string plataforma { get; set; }
        public Nullable<bool> doblado { get; set; }
        public string genero { get; set; }
        public string distribuidora { get; set; }
        public string desarolladora { get; set; }
        public Nullable<bool> multijugador { get; set; }
        public string tipo_alquiler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}
