//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.VideoClub.Backend.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videoclubEntities : DbContext
    {
        public videoclubEntities()
            : base("name=videoclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actor { get; set; }
        public virtual DbSet<alquiler> alquiler { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<incidencia> incidencia { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<juego> juego { get; set; }
        public virtual DbSet<pelicula> pelicula { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<tipo_alquiler> tipo_alquiler { get; set; }
        public virtual DbSet<tipo_incidencia> tipo_incidencia { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
