//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.VideoClub.Backend.Modelo
{
    using proyecto.VideoClub.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pelicula : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pelicula()
        {
            this.producto = new HashSet<producto>();
            this.actor = new HashSet<actor>();
            this.genero = new HashSet<genero>();
        }
    
        public int id_pelicula { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(30)]
        public string titulo_original { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(30)]
        public string pais { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        
        public Nullable<int> duracion { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(300)]
        public string sinopsis { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string director { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(30)]
        public string formato { get; set; }
       
        public string tipo_alquiler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor> actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genero> genero { get; set; }
    }
}
